version: "2"
services:
  denounce_ms:
    container_name: app
    restart: always
    build: .
    ports:
      - "3001:3000"
    links:
      - denounce_db
  denounce_db:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27019:27017"
